Introduce usdp gauge
unitprotocol/fee-distribution pull request #2
Opened 2021-09-09 14:26 UTC by 34x4p08

2021-09-13 15:52 UTC, Eenae requested changes
Is there a test or migration wiring the contracts together? So that I can check the wiring.

2021-09-13 15:52 UTC, Eenae commented on contracts/USDPGauge.sol
> +        usdp.safeTransferFrom(owner(), address(this), reward);
Are you sure it's `owner()`, not `msg.sender`?

2021-09-14 08:47 UTC, Eenae commented
Also I suggest renaming `USDPGauge` to USDP staking, 
and making DUCK/USDP ratios configurable: `% of liquidationFee to qDuck`, `% of stabilityFee to qDuck`.

2021-09-15 11:50 UTC, Eenae requested changes

2021-09-15 17:12 UTC, Eenae commented
Interest capitalization function could be implemented, which is immediate gas-efficient depositing of claimed rewards.

2021-09-16 12:20 UTC, 34x4p08 commented on contracts/Foundation.sol
> +  address public auction;
Added gov control over this

2021-09-16 12:22 UTC, 34x4p08 commented on contracts/Foundation.sol
> +    usdp.transfer(qDuckDistribution, qDuckDistributionAmount);
acknowledged

2021-09-16 12:22 UTC, 34x4p08 commented on contracts/Foundation.sol
> +    uint qDuckDistributionAmount = usdpBalance.sub(usdpGaugeAmount);
Fixed the calculation

2021-09-16 12:23 UTC, 34x4p08 commented on contracts/StabilityFeeCollector.sol
> +  IUSDPGauge public constant usdpGauge = IUSDPGauge(address(0));
Test case added

2021-09-16 12:23 UTC, 34x4p08 commented on contracts/USDPGauge.sol
> +    using SafeMath for uint;
applied

2021-09-16 12:23 UTC, 34x4p08 commented on contracts/USDPGauge.sol
> +        usdp.safeTransferFrom(owner(), address(this), reward);
fixed

2021-09-16 12:26 UTC, 34x4p08 commented on contracts/USDPGauge.sol
> +    using Address for address;
Cleaned up

2021-09-16 12:27 UTC, 34x4p08 commented on contracts/USDPGauge.sol
> +        uint reward = earned(user);
applied

2021-09-16 12:27 UTC, 34x4p08 commented on contracts/USDPGauge.sol
> +            return rewardPerTokenStored;
Can be resolved by making a pre-deposit

2021-09-16 12:27 UTC, 34x4p08 commented on contracts/USDPGauge.sol
> +            rewards[user] = 0;
applied

2021-09-16 12:29 UTC, 34x4p08 commented
> Also I suggest renaming `USDPGauge` to USDP staking,
> and making DUCK/USDP ratios configurable: `% of liquidationFee to qDuck`, `% of stabilityFee to qDuck`.
> Interest capitalization function could be implemented, which is immediate gas-efficient depositing of claimed rewards.

Implemented

2021-09-22 16:07 UTC, Eenae approved these changes

2021-09-23 13:17 UTC, merged